// Serves the Zwift custom workouts (.zwo) generated by training/zwift/build.js
// at /zwift (an index page) and /zwift/<slug>.zwo (the file itself, as a
// download). The .zwo files are bundled into the worker as text modules via
// the `rules` block in wrangler.toml, so a deploy after `node
// training/zwift/build.js` is all it takes to publish a new workout.

import { pageShell } from "./theme.js";
import index from "../training/zwift/index.json";

import easySpin30 from "../training/zwift/easy-spin-30.zwo";
import z245 from "../training/zwift/rebuild-z2-45.zwo";
import z260 from "../training/zwift/rebuild-z2-60.zwo";
import tempo3x5 from "../training/zwift/rebuild-tempo-3x5.zwo";
import ftp20 from "../training/zwift/ftp-test-20.zwo";
import ftpPlusZ2 from "../training/zwift/ftp-test-plus-z2-90.zwo";
import long75 from "../training/zwift/long-z2-75.zwo";
import long90 from "../training/zwift/long-z2-90.zwo";
import long105 from "../training/zwift/long-z2-105.zwo";
import long120 from "../training/zwift/long-z2-120.zwo";
import long135 from "../training/zwift/long-z2-135.zwo";
import long150 from "../training/zwift/long-z2-150.zwo";
import long165 from "../training/zwift/long-z2-165.zwo";
import long180 from "../training/zwift/long-z2-180.zwo";

const FILES = {
  "easy-spin-30": easySpin30,
  "rebuild-z2-45": z245,
  "rebuild-z2-60": z260,
  "rebuild-tempo-3x5": tempo3x5,
  "ftp-test-20": ftp20,
  "ftp-test-plus-z2-90": ftpPlusZ2,
  "long-z2-75": long75,
  "long-z2-90": long90,
  "long-z2-105": long105,
  "long-z2-120": long120,
  "long-z2-135": long135,
  "long-z2-150": long150,
  "long-z2-165": long165,
  "long-z2-180": long180,
};

function esc(s) {
  if (s === null || s === undefined) return "";
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

export function zwiftFile(slug) {
  const body = FILES[slug];
  if (!body) return null;
  return new Response(body, {
    headers: {
      "content-type": "application/xml; charset=utf-8",
      "content-disposition": `attachment; filename="${slug}.zwo"`,
      "cache-control": "public, max-age=300",
    },
  });
}

export function renderZwiftIndex() {
  const groups = [
    { title: "Midweek", slugs: ["easy-spin-30", "rebuild-z2-45", "rebuild-z2-60", "rebuild-tempo-3x5"] },
    { title: "Tests", slugs: ["ftp-test-20", "ftp-test-plus-z2-90"] },
    { title: "Long rides — rebuild block, +15 min a week when it happens", slugs: ["long-z2-75", "long-z2-90", "long-z2-105", "long-z2-120", "long-z2-135", "long-z2-150", "long-z2-165", "long-z2-180"] },
  ];
  const bySlug = Object.fromEntries(index.map((w) => [w.slug, w]));

  const body = `
  <span class="chapter-label">Exhibit Golf — The Belafonte</span>
  <h1>Engine Room</h1>
  <p class="subhead">Zwift workouts, written to the plan</p>
  <p class="lede">Every ride on the rebuild-block menu as a Zwift custom workout. Power targets are percentages of the FTP set in Zwift, so the files never need to change when the number does. Set Zwift's FTP to 133 W until the 20-minute test says otherwise.</p>

  <nav class="topnav"><a href="/">Chart table</a><a href="/log">Ship's log</a><a href="/zwift" class="here">Engine room</a></nav>

  <div class="stripe"></div>

  <section>
    <h2>Installing</h2>
    <ol class="steps">
      <li>On a Mac or PC that has Zwift installed, open <code>Documents / Zwift / Workouts / &lt;your Zwift ID&gt;</code>. The ID is the numeric folder already there.</li>
      <li>Download the files below into that folder.</li>
      <li>Open Zwift. They appear under <b>Workouts → Custom Workouts</b>, and sync to iPad, iPhone, and Apple TV on the same account within a few minutes. Restart the app on the other device if they don't.</li>
    </ol>
    <p class="note">The FTP tests run the 20-minute block with ERG off (a "free ride" segment) so the trainer stops setting resistance and you set the effort. Everything else runs in ERG. Ride in Zwift with Zwift linked to Strava so the power lands in the log.</p>
  </section>

  ${groups
    .map(
      (g) => `<section>
    <h2>${esc(g.title)}</h2>
    ${g.slugs
      .map((slug) => {
        const w = bySlug[slug];
        if (!w) return "";
        return `<div class="card wo">
      <a class="dl" href="/zwift/${esc(slug)}.zwo" download>↓ .zwo</a>
      <h3>${esc(w.name.replace(/^Belafonte — /, ""))}</h3>
      <p>${esc(w.description)}</p>
    </div>`;
      })
      .join("")}
  </section>`
    )
    .join("")}`;

  const extraCss = `
ol.steps{padding-left:22px;font-size:14.5px}
ol.steps li{margin:8px 0}
code{font-family:var(--mono);font-size:13px;background:var(--card-bg);border:1px solid var(--border);padding:1px 6px}
.note{font-size:12.5px;color:var(--muted)}
.card.wo{padding-right:110px}
.card.wo .dl{position:absolute;top:14px;right:16px;font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;text-decoration:none;color:var(--ivory);background:var(--ocean-deep);padding:6px 10px}
:root[data-theme="dark"] .card.wo .dl{background:var(--ivory);color:var(--ocean-deep)}
@media (prefers-color-scheme: dark){:root:not([data-theme="light"]) .card.wo .dl{background:var(--ivory);color:var(--ocean-deep)}}
@media (max-width:520px){.card.wo{padding-right:24px}.card.wo .dl{position:static;display:inline-block;margin-bottom:10px}}
`;

  return pageShell({
    title: "Engine Room — The Belafonte",
    description: "Zwift custom workouts matching the Road to 140.6 training plan.",
    body,
    extraCss,
  });
}
